import { string, object } from 'yup';

import { CHARCOUNT, MESSAGES } from './checkout.constants';

const trimString = string().trim();
const phoneRegExp =
  /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;

export const checkoutSchema = object().shape({
  firstname: trimString
    .min(CHARCOUNT.FIRSTNAME_MIN, MESSAGES.FIRSTNAME_MIN)
    .max(CHARCOUNT.FIRSTNAME_MAX, MESSAGES.FIRSTNAME_MAX)
    .required(MESSAGES.FIRSTNAME_IS_REQUIRED),
  lastname: trimString
    .min(CHARCOUNT.LASTNAME_MIN, MESSAGES.LASTNAME_MIN)
    .max(CHARCOUNT.LASTNAME_MAX, MESSAGES.LASTNAME_MAX)
    .required(MESSAGES.LASTNAME_IS_REQUIRED),
  notificationEmail: trimString.email(MESSAGES.EMAIL_IS_VALID).required(MESSAGES.EMAIL_REQUIRED),
  phone: trimString
    .required(MESSAGES.PHONE_NUMBER_IS_REQUIRED)
    .matches(phoneRegExp, MESSAGES.PHONE_NUMBER_IS_NOT_VALID),
  address: trimString
    .min(CHARCOUNT.ADDRESS_MIN, MESSAGES.ADDRESS_MIN)
    .max(CHARCOUNT.ADDRESS_MAX, MESSAGES.ADDRESS_MAX)
    .required(MESSAGES.ADDRESS_IS_REQUIRED),
  addresseeFirstname: trimString
    .min(CHARCOUNT.ADDRESSEE_FIRSTNAME_MIN, MESSAGES.ADDRESSEE_FIRSTNAME_MIN)
    .max(CHARCOUNT.ADDRESSEE_FIRSTNAME_MAX, MESSAGES.ADDRESSEE_FIRSTNAME_MAX)
    .required(MESSAGES.ADDRESSEE_FIRSTNAME_IS_REQUIRED),
  addresseeLastname: trimString
    .min(CHARCOUNT.ADDRESSEE_LASTNAME_MIN, MESSAGES.ADDRESSEE_LASTNAME_MIN)
    .max(CHARCOUNT.ADDRESSEE_LASTNAME_MAX, MESSAGES.ADDRESSEE_LASTNAME_MAX)
    .required(MESSAGES.ADDRESSEE_LASTNAME_IS_REQUIRED),
  deliveryAddress: trimString
    .min(CHARCOUNT.DELIVERY_ADDRESS_MIN, MESSAGES.DELIVERY_ADDRESS_MIN)
    .max(CHARCOUNT.DELIVERY_ADDRESS_MAX, MESSAGES.DELIVERY_ADDRESS_MAX)
    .required(MESSAGES.DELIVERY_ADDRESS_IS_REQUIRED),
  deliveryCountry: trimString
    .min(CHARCOUNT.DELIVERY_COUNTRY_MIN, MESSAGES.DELIVERY_COUNTRY_MIN)
    .max(CHARCOUNT.DELIVERY_COUNTRY_MAX, MESSAGES.DELIVERY_COUNTRY_MAX)
    .required(MESSAGES.DELIVERY_COUNTRY_IS_REQUIRED),
  deliveryCity: trimString
    .min(CHARCOUNT.DELIVERY_CITY_MIN, MESSAGES.DELIVERY_CITY_MIN)
    .max(CHARCOUNT.DELIVERY_CITY_MAX, MESSAGES.DELIVERY_CITY_MAX)
    .required(MESSAGES.DELIVERY_CITY_IS_REQUIRED),
  deliveryPostalCode: trimString
    .min(CHARCOUNT.DELIVERY_POSTAL_CODE_MIN, MESSAGES.DELIVERY_POSTAL_CODE_MIN)
    .max(CHARCOUNT.DELIVERY_POSTAL_CODE_MAX, MESSAGES.DELIVERY_POSTAL_CODE_MAX)
    .required(MESSAGES.DELIVERY_POSTAL_CODE_IS_REQUIRED),
});
