export const CHARCOUNT = {
  FIRSTNAME_MIN: 2,
  FIRSTNAME_MAX: 50,
  LASTNAME_MIN: 2,
  LASTNAME_MAX: 50,
  ADDRESS_MIN: 2,
  ADDRESS_MAX: 100,
  ADDRESSEE_FIRSTNAME_MIN: 2,
  ADDRESSEE_FIRSTNAME_MAX: 50,
  ADDRESSEE_LASTNAME_MIN: 2,
  ADDRESSEE_LASTNAME_MAX: 50,
  DELIVERY_ADDRESS_MIN: 2,
  DELIVERY_ADDRESS_MAX: 100,
  DELIVERY_COUNTRY_MIN: 2,
  DELIVERY_COUNTRY_MAX: 100,
  DELIVERY_CITY_MIN: 2,
  DELIVERY_CITY_MAX: 100,
  DELIVERY_POSTAL_CODE_MIN: 2,
  DELIVERY_POSTAL_CODE_MAX: 6,
};

export const MESSAGES = {
  FIRSTNAME_IS_REQUIRED: 'first name is a required field',
  FIRSTNAME_MIN: `first name must be at least ${CHARCOUNT.FIRSTNAME_MIN} characters`,
  FIRSTNAME_MAX: `first name must be shorter than ${CHARCOUNT.FIRSTNAME_MAX} characters`,
  LASTNAME_IS_REQUIRED: 'last name is a required field',
  LASTNAME_MIN: `last name must be at least ${CHARCOUNT.LASTNAME_MIN} characters`,
  LASTNAME_MAX: `last name must be shorter than ${CHARCOUNT.LASTNAME_MAX} characters`,
  EMAIL_REQUIRED: 'notification email is a required field',
  EMAIL_IS_VALID: 'notification email must be a valid email',
  PHONE_NUMBER_IS_REQUIRED: 'phone number is a required field',
  PHONE_NUMBER_IS_NOT_VALID: 'phone number is not valid',
  ADDRESS_IS_REQUIRED: 'address is a required field',
  ADDRESS_MIN: `address must be at least ${CHARCOUNT.ADDRESS_MIN} characters`,
  ADDRESS_MAX: `address must be shorter than ${CHARCOUNT.ADDRESS_MAX} characters`,
  ADDRESSEE_FIRSTNAME_IS_REQUIRED: 'addressee first name is a required field',
  ADDRESSEE_FIRSTNAME_MIN: `addressee first name must be at least ${CHARCOUNT.ADDRESSEE_FIRSTNAME_MIN} characters`,
  ADDRESSEE_FIRSTNAME_MAX: `addressee first name must be shorter than ${CHARCOUNT.ADDRESSEE_FIRSTNAME_MAX} characters`,
  ADDRESSEE_LASTNAME_IS_REQUIRED: 'addressee last name is a required field',
  ADDRESSEE_LASTNAME_MIN: `addressee last name must be at least ${CHARCOUNT.ADDRESSEE_LASTNAME_MIN} characters`,
  ADDRESSEE_LASTNAME_MAX: `addressee last name must be shorter than ${CHARCOUNT.ADDRESSEE_LASTNAME_MAX} characters`,
  DELIVERY_ADDRESS_IS_REQUIRED: 'delivery address is a required field',
  DELIVERY_ADDRESS_MIN: `delivery address must be at least ${CHARCOUNT.DELIVERY_ADDRESS_MIN} characters`,
  DELIVERY_ADDRESS_MAX: `delivery address must be shorter than ${CHARCOUNT.DELIVERY_ADDRESS_MAX} characters`,
  DELIVERY_COUNTRY_IS_REQUIRED: 'delivery country is a required field',
  DELIVERY_COUNTRY_MIN: `delivery country must be at least ${CHARCOUNT.DELIVERY_COUNTRY_MIN} characters`,
  DELIVERY_COUNTRY_MAX: `delivery country must be shorter than ${CHARCOUNT.DELIVERY_COUNTRY_MAX} characters`,
  DELIVERY_CITY_IS_REQUIRED: 'delivery city is a required field',
  DELIVERY_CITY_MIN: `delivery city must be at least ${CHARCOUNT.DELIVERY_CITY_MIN} characters`,
  DELIVERY_CITY_MAX: `delivery city must be shorter than ${CHARCOUNT.DELIVERY_CITY_MAX} characters`,
  DELIVERY_POSTAL_CODE_IS_REQUIRED: 'delivery postal code is a required field',
  DELIVERY_POSTAL_CODE_MIN: `delivery postal code must be at least ${CHARCOUNT.DELIVERY_POSTAL_CODE_MIN} characters`,
  DELIVERY_POSTAL_CODE_MAX: `delivery postal code must be shorter than ${CHARCOUNT.DELIVERY_POSTAL_CODE_MAX} characters`,
};
